<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>About</title>
    <link rel="stylesheet" href="css/style.css">
</head>

<body>

   <nav class="navbar">
    <a href="/characters">Home</a>
    <a href="/characters/createForm">Add a Character</a>
</nav>

    <h1>About This Website</h1>

    <img class="large-img" src="images/group1.jpg" alt="Group photo">
    <p>
        This website was created for a class project to showcase fictional
        characters from different universes. I chose this theme because I grew up watching Marvel, DC, and other
        superhero shows and movies, and also learned about many characters from video games. This project allowed me to practice
        HTML, CSS, and basic JavaScript.
    </p>

</body>

</html>